apiVersion: v1
kind: Service
metadata:
  name: linkding-nodeport
  namespace: linkding
  labels:
    app: linkding
spec:
  type: NodePort
  selector:
    app: linkding
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
    protocol: TCP
